'''
   The keywords used in MAlice. These are very useful for syntax checking purposes.
'''

ARRAYDECL = "had" 
ARRAY = "spider"
ASSIGN = "became"
CHAR = "letter"
CHR = "'"
CLOSE = "closed"
DEC = "drank"
DECL = "was a"
ELSE = "or"
ELSE_IF = "or maybe"    
END_STATEMENT1 = "and"
END_STATEMENT2 = "but"
END_STATEMENT3 = "then"
ENDIF = "because Alice was unsure which"
ENDWHILE = "enough times"
FULLSTOP = "."
IF1 = "either"
IF2 = "perhaps"
INC = "ate"
INT = "number"
LEFTOPEN = "'s"
LPAREN = "("
MAINF = "The looking-glass hatta"
OF = "of"
OPEN = "opened"
PRINT1 = "said Alice"
PRINT2 = "spoke"
READ =   "what was"  
RET = "Alice found"     
RIGHTCLOSE = "piece"
RPAREN = ")"
SAID = "said"
START_WHILE = "because"
STRING = "sentence" 
TYPE_OF_FUNCTION = "contained a"
THEN = "so"
TYPEF = "The room"
VOIDF = "The looking-glass"
WHILE = "eventually"
